server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-demo
  
  # 数据源配置 - MySQL 8
  datasource:
    url: jdbc:mysql://localhost:3306/food_street?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # 关闭H2控制台（切换MySQL）
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql,classpath:checkin-test-data.sql

# 日志配置
logging:
  level:
    com.example: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI & Knife4j 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /auth/**, /users/**, /health/**, /cultural/**, /merchants/**, /products/**, /merchant-qualifications/**, /reservations/**, /checkins/**, /reviews/**, /activities/**, /venues/**, /hygiene-checks/**, /traffic/**, /revenues/**, /notifications/**, /system-logs/**, /system/**, /test/**

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-debug: true
    enable-open-api: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true
