server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-demo
  
  # Session配置
  session:
    store-type: none  # 使用内存存储
    timeout: 3600  # Session超时时间（秒）
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/food_street?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # SQL初始化配置
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# 日志配置
logging:
  level:
    com.example: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI & Knife4j 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /auth/**, /users/**, /health/**, /cultural/**, /merchants/**, /products/**, /merchant-qualifications/**, /reservations/**, /checkins/**, /reviews/**, /activities/**, /venues/**, /hygiene-checks/**, /traffic/**, /revenues/**, /notifications/**, /system-logs/**, /system/**, /test/**

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-debug: true
    enable-open-api: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: bo-spj
    domain: https://bo-spj.oss-cn-beijing.aliyuncs.com
    # 文件上传配置
    upload:
      max-file-size: 10MB
      max-request-size: 50MB
      allowed-extensions: jpg,jpeg,png,gif,bmp,webp
      # 文件存储路径配置
      paths:
        avatar: avatar/
        merchant: merchant/
        product: product/
        cultural: cultural/
        route: route/
        temp: temp/
